image:
  file: .gitpod.Dockerfile

tasks:
  - init: pipenv install -e .

vscode:
  extensions:
    - hbenl.vscode-test-explorer@2.19.1:GtY0wSp3pjUeyKXi8mFMnQ==
    - littlefoxteam.vscode-python-test-adapter@0.4.5:AjFDI5oxInml/vtCNspL6w==